### ISSUE TITLE
Done button isn't present

### ISSUE THREAD

**Issue by MPS64** [ayunami2000/ayunpictonode#2]
Hey! This is a really cool revival of a long dead project. Unfortunately, me and my friends can't use it due to the done button suddenly disappearing? I tested it a few days ago, too. It worked fine. Please fix this as soon as possible!
![image_2022-08-15_013021979](https://user-images.githubusercontent.com/69330570/184581424-930b25ee-01c6-495b-8bf2-4c2c73e7cf41.png) 
![image_2022-08-15_013049817](https://user-images.githubusercontent.com/69330570/184581449-e1a15cb6-7741-41b4-bab2-6646912b1bfa.png)

**Comment by ayunami2000** [comment]
You click on "PictoChat Online" not "Done"

**Comment by MPS64** [comment]
well uh it won't work lol

**Comment by ayunami2000** [comment]
What URL are you using?

**Comment by MPS64** [comment]
ahh I think I was using the wrong link. Apologies.
